version: '1'

services:
  authorizationservice1:
    image: 'authorizeservice:1.0'
    ports:
      - '8080'
    environment:
      INST_NUM: 1
  authorizationservice2:
    image: 'authorizeservice:1.0'
    ports:
      - '8080'
    environment:
      INST_NUM: 2
    depends_on:
      - authorizationservice1